### ISSUE TITLE
Does not build with DMD v2.084.0

### ISSUE THREAD

**Issue by streaps** [rejectedsoftware/vibenews#41]
vibenews master does not build with DMD v2.084.0 on Ubuntu 18.04

`dub` fails on stdx-allocator 2.77.0  
`dub upgrade` introduces other problems  
Setting stdx-allocator to version "2.77.5" in dub.selections.json fixes the first build problem, but then there is some openssl error.

/home/forum/.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:467: undefined reference to `SSLv23_client_method'
[...]
Error: linker exited with status 1

same with newest vibe-d:

/root/.dub/packages/vibe-d-0.8.5-alpha.2/vibe-d/tls/vibe/stream/openssl.d:585: undefined reference to `SSLv23_client_method'

If I understand it correctly that is a known issue with vibe-d and openssl 1.1.0. Any idea how to achieve a successful build?

**Comment by s-ludwig** [comment]
Try building with `dub --override-config vibe-d:tls/openssl-1.1` - the default is still to link against OpenSSL 1.0.x (should be changed with the next version).

**Comment by streaps** [comment]
that works!

**Comment by s-ludwig** [comment]
The latest vibe.d versions use 1.1.x as the default, so this should also work by default now.
